version: 2
updates:
  - package-ecosystem: "github-actions"
    schedule:
      interval: weekly
    directory: "/"
  - package-ecosystem: gomod
    schedule:
      interval: weekly
    directories:
      - "/"
      - "/integrationtest/chaincode/*"
    groups:
      # Single PR to update a specific dependency in multiple directories.
      go:
        group-by: dependency-name
  - package-ecosystem: npm
    schedule:
      interval: weekly
    directory: "/integrationtest"
