#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: fabric-contract-api-go
  description: Packages for the implementation of the contract API for use in
    Go chaincode
  homepage: https://wiki.hyperledger.org/display/fabric
  default_branch: master
  has_downloads: true
  has_issues: false
  has_projects: false
  has_wiki: false
  archived: false
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
