version: "2"
linters:
  default: none
  enable:
    - cyclop
    - errcheck
    - errname
    - errorlint
    - gocognit
    - goheader
    - gosec
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - staticcheck
    - testifylint
    - unused
    - usetesting
  settings:
    cyclop:
      max-complexity: 18
    gocognit:
      min-complexity: 26
    goheader:
      template: |-
        Copyright the Hyperledger Fabric contributors. All rights reserved.
        SPDX-License-Identifier: Apache-2.0
    staticcheck:
      checks:
        - all
        - -ST1000
  exclusions:
    generated: strict
    presets:
      - common-false-positives
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: strict
