structname: Mock{{.InterfaceName | firstUpper}}
template: testify
packages:
  github.com/hyperledger/fabric-chaincode-go/v2/shim:
    interfaces:
      ChaincodeStubInterface:
        configs:
          - pkgname: contractapi
            dir: contractapi
            structname: MockChaincodeStub
