// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package contractapi

import (
	"github.com/hyperledger/fabric-chaincode-go/v2/shim"
	"github.com/hyperledger/fabric-protos-go-apiv2/peer"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// NewMockChaincodeStub creates a new instance of MockChaincodeStub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChaincodeStub(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChaincodeStub {
	mock := &MockChaincodeStub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChaincodeStub is an autogenerated mock type for the ChaincodeStubInterface type
type MockChaincodeStub struct {
	mock.Mock
}

type MockChaincodeStub_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChaincodeStub) EXPECT() *MockChaincodeStub_Expecter {
	return &MockChaincodeStub_Expecter{mock: &_m.Mock}
}

// CreateCompositeKey provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) CreateCompositeKey(objectType string, attributes []string) (string, error) {
	ret := _mock.Called(objectType, attributes)

	if len(ret) == 0 {
		panic("no return value specified for CreateCompositeKey")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []string) (string, error)); ok {
		return returnFunc(objectType, attributes)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []string) string); ok {
		r0 = returnFunc(objectType, attributes)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = returnFunc(objectType, attributes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_CreateCompositeKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCompositeKey'
type MockChaincodeStub_CreateCompositeKey_Call struct {
	*mock.Call
}

// CreateCompositeKey is a helper method to define mock.On call
//   - objectType
//   - attributes
func (_e *MockChaincodeStub_Expecter) CreateCompositeKey(objectType interface{}, attributes interface{}) *MockChaincodeStub_CreateCompositeKey_Call {
	return &MockChaincodeStub_CreateCompositeKey_Call{Call: _e.mock.On("CreateCompositeKey", objectType, attributes)}
}

func (_c *MockChaincodeStub_CreateCompositeKey_Call) Run(run func(objectType string, attributes []string)) *MockChaincodeStub_CreateCompositeKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string))
	})
	return _c
}

func (_c *MockChaincodeStub_CreateCompositeKey_Call) Return(s string, err error) *MockChaincodeStub_CreateCompositeKey_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockChaincodeStub_CreateCompositeKey_Call) RunAndReturn(run func(objectType string, attributes []string) (string, error)) *MockChaincodeStub_CreateCompositeKey_Call {
	_c.Call.Return(run)
	return _c
}

// DelPrivateData provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) DelPrivateData(collection string, key string) error {
	ret := _mock.Called(collection, key)

	if len(ret) == 0 {
		panic("no return value specified for DelPrivateData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(collection, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChaincodeStub_DelPrivateData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DelPrivateData'
type MockChaincodeStub_DelPrivateData_Call struct {
	*mock.Call
}

// DelPrivateData is a helper method to define mock.On call
//   - collection
//   - key
func (_e *MockChaincodeStub_Expecter) DelPrivateData(collection interface{}, key interface{}) *MockChaincodeStub_DelPrivateData_Call {
	return &MockChaincodeStub_DelPrivateData_Call{Call: _e.mock.On("DelPrivateData", collection, key)}
}

func (_c *MockChaincodeStub_DelPrivateData_Call) Run(run func(collection string, key string)) *MockChaincodeStub_DelPrivateData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_DelPrivateData_Call) Return(err error) *MockChaincodeStub_DelPrivateData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChaincodeStub_DelPrivateData_Call) RunAndReturn(run func(collection string, key string) error) *MockChaincodeStub_DelPrivateData_Call {
	_c.Call.Return(run)
	return _c
}

// DelState provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) DelState(key string) error {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for DelState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChaincodeStub_DelState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DelState'
type MockChaincodeStub_DelState_Call struct {
	*mock.Call
}

// DelState is a helper method to define mock.On call
//   - key
func (_e *MockChaincodeStub_Expecter) DelState(key interface{}) *MockChaincodeStub_DelState_Call {
	return &MockChaincodeStub_DelState_Call{Call: _e.mock.On("DelState", key)}
}

func (_c *MockChaincodeStub_DelState_Call) Run(run func(key string)) *MockChaincodeStub_DelState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_DelState_Call) Return(err error) *MockChaincodeStub_DelState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChaincodeStub_DelState_Call) RunAndReturn(run func(key string) error) *MockChaincodeStub_DelState_Call {
	_c.Call.Return(run)
	return _c
}

// FinishWriteBatch provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) FinishWriteBatch() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FinishWriteBatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChaincodeStub_FinishWriteBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishWriteBatch'
type MockChaincodeStub_FinishWriteBatch_Call struct {
	*mock.Call
}

// FinishWriteBatch is a helper method to define mock.On call
func (_e *MockChaincodeStub_Expecter) FinishWriteBatch() *MockChaincodeStub_FinishWriteBatch_Call {
	return &MockChaincodeStub_FinishWriteBatch_Call{Call: _e.mock.On("FinishWriteBatch")}
}

func (_c *MockChaincodeStub_FinishWriteBatch_Call) Run(run func()) *MockChaincodeStub_FinishWriteBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChaincodeStub_FinishWriteBatch_Call) Return(err error) *MockChaincodeStub_FinishWriteBatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChaincodeStub_FinishWriteBatch_Call) RunAndReturn(run func() error) *MockChaincodeStub_FinishWriteBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllStatesCompositeKeyWithPagination provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetAllStatesCompositeKeyWithPagination(pageSize int32, bookmark string) (shim.StateQueryIteratorInterface, *peer.QueryResponseMetadata, error) {
	ret := _mock.Called(pageSize, bookmark)

	if len(ret) == 0 {
		panic("no return value specified for GetAllStatesCompositeKeyWithPagination")
	}

	var r0 shim.StateQueryIteratorInterface
	var r1 *peer.QueryResponseMetadata
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(int32, string) (shim.StateQueryIteratorInterface, *peer.QueryResponseMetadata, error)); ok {
		return returnFunc(pageSize, bookmark)
	}
	if returnFunc, ok := ret.Get(0).(func(int32, string) shim.StateQueryIteratorInterface); ok {
		r0 = returnFunc(pageSize, bookmark)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shim.StateQueryIteratorInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int32, string) *peer.QueryResponseMetadata); ok {
		r1 = returnFunc(pageSize, bookmark)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*peer.QueryResponseMetadata)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(int32, string) error); ok {
		r2 = returnFunc(pageSize, bookmark)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockChaincodeStub_GetAllStatesCompositeKeyWithPagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllStatesCompositeKeyWithPagination'
type MockChaincodeStub_GetAllStatesCompositeKeyWithPagination_Call struct {
	*mock.Call
}

// GetAllStatesCompositeKeyWithPagination is a helper method to define mock.On call
//   - pageSize
//   - bookmark
func (_e *MockChaincodeStub_Expecter) GetAllStatesCompositeKeyWithPagination(pageSize interface{}, bookmark interface{}) *MockChaincodeStub_GetAllStatesCompositeKeyWithPagination_Call {
	return &MockChaincodeStub_GetAllStatesCompositeKeyWithPagination_Call{Call: _e.mock.On("GetAllStatesCompositeKeyWithPagination", pageSize, bookmark)}
}

func (_c *MockChaincodeStub_GetAllStatesCompositeKeyWithPagination_Call) Run(run func(pageSize int32, bookmark string)) *MockChaincodeStub_GetAllStatesCompositeKeyWithPagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int32), args[1].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_GetAllStatesCompositeKeyWithPagination_Call) Return(stateQueryIteratorInterface shim.StateQueryIteratorInterface, queryResponseMetadata *peer.QueryResponseMetadata, err error) *MockChaincodeStub_GetAllStatesCompositeKeyWithPagination_Call {
	_c.Call.Return(stateQueryIteratorInterface, queryResponseMetadata, err)
	return _c
}

func (_c *MockChaincodeStub_GetAllStatesCompositeKeyWithPagination_Call) RunAndReturn(run func(pageSize int32, bookmark string) (shim.StateQueryIteratorInterface, *peer.QueryResponseMetadata, error)) *MockChaincodeStub_GetAllStatesCompositeKeyWithPagination_Call {
	_c.Call.Return(run)
	return _c
}

// GetArgs provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetArgs() [][]byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetArgs")
	}

	var r0 [][]byte
	if returnFunc, ok := ret.Get(0).(func() [][]byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}
	return r0
}

// MockChaincodeStub_GetArgs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArgs'
type MockChaincodeStub_GetArgs_Call struct {
	*mock.Call
}

// GetArgs is a helper method to define mock.On call
func (_e *MockChaincodeStub_Expecter) GetArgs() *MockChaincodeStub_GetArgs_Call {
	return &MockChaincodeStub_GetArgs_Call{Call: _e.mock.On("GetArgs")}
}

func (_c *MockChaincodeStub_GetArgs_Call) Run(run func()) *MockChaincodeStub_GetArgs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChaincodeStub_GetArgs_Call) Return(bytess [][]byte) *MockChaincodeStub_GetArgs_Call {
	_c.Call.Return(bytess)
	return _c
}

func (_c *MockChaincodeStub_GetArgs_Call) RunAndReturn(run func() [][]byte) *MockChaincodeStub_GetArgs_Call {
	_c.Call.Return(run)
	return _c
}

// GetArgsSlice provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetArgsSlice() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetArgsSlice")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetArgsSlice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArgsSlice'
type MockChaincodeStub_GetArgsSlice_Call struct {
	*mock.Call
}

// GetArgsSlice is a helper method to define mock.On call
func (_e *MockChaincodeStub_Expecter) GetArgsSlice() *MockChaincodeStub_GetArgsSlice_Call {
	return &MockChaincodeStub_GetArgsSlice_Call{Call: _e.mock.On("GetArgsSlice")}
}

func (_c *MockChaincodeStub_GetArgsSlice_Call) Run(run func()) *MockChaincodeStub_GetArgsSlice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChaincodeStub_GetArgsSlice_Call) Return(bytes []byte, err error) *MockChaincodeStub_GetArgsSlice_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockChaincodeStub_GetArgsSlice_Call) RunAndReturn(run func() ([]byte, error)) *MockChaincodeStub_GetArgsSlice_Call {
	_c.Call.Return(run)
	return _c
}

// GetBinding provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetBinding() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBinding")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBinding'
type MockChaincodeStub_GetBinding_Call struct {
	*mock.Call
}

// GetBinding is a helper method to define mock.On call
func (_e *MockChaincodeStub_Expecter) GetBinding() *MockChaincodeStub_GetBinding_Call {
	return &MockChaincodeStub_GetBinding_Call{Call: _e.mock.On("GetBinding")}
}

func (_c *MockChaincodeStub_GetBinding_Call) Run(run func()) *MockChaincodeStub_GetBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChaincodeStub_GetBinding_Call) Return(bytes []byte, err error) *MockChaincodeStub_GetBinding_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockChaincodeStub_GetBinding_Call) RunAndReturn(run func() ([]byte, error)) *MockChaincodeStub_GetBinding_Call {
	_c.Call.Return(run)
	return _c
}

// GetChannelID provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetChannelID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChannelID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockChaincodeStub_GetChannelID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannelID'
type MockChaincodeStub_GetChannelID_Call struct {
	*mock.Call
}

// GetChannelID is a helper method to define mock.On call
func (_e *MockChaincodeStub_Expecter) GetChannelID() *MockChaincodeStub_GetChannelID_Call {
	return &MockChaincodeStub_GetChannelID_Call{Call: _e.mock.On("GetChannelID")}
}

func (_c *MockChaincodeStub_GetChannelID_Call) Run(run func()) *MockChaincodeStub_GetChannelID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChaincodeStub_GetChannelID_Call) Return(s string) *MockChaincodeStub_GetChannelID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockChaincodeStub_GetChannelID_Call) RunAndReturn(run func() string) *MockChaincodeStub_GetChannelID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCreator provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetCreator() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCreator")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetCreator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCreator'
type MockChaincodeStub_GetCreator_Call struct {
	*mock.Call
}

// GetCreator is a helper method to define mock.On call
func (_e *MockChaincodeStub_Expecter) GetCreator() *MockChaincodeStub_GetCreator_Call {
	return &MockChaincodeStub_GetCreator_Call{Call: _e.mock.On("GetCreator")}
}

func (_c *MockChaincodeStub_GetCreator_Call) Run(run func()) *MockChaincodeStub_GetCreator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChaincodeStub_GetCreator_Call) Return(bytes []byte, err error) *MockChaincodeStub_GetCreator_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockChaincodeStub_GetCreator_Call) RunAndReturn(run func() ([]byte, error)) *MockChaincodeStub_GetCreator_Call {
	_c.Call.Return(run)
	return _c
}

// GetDecorations provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetDecorations() map[string][]byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDecorations")
	}

	var r0 map[string][]byte
	if returnFunc, ok := ret.Get(0).(func() map[string][]byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]byte)
		}
	}
	return r0
}

// MockChaincodeStub_GetDecorations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDecorations'
type MockChaincodeStub_GetDecorations_Call struct {
	*mock.Call
}

// GetDecorations is a helper method to define mock.On call
func (_e *MockChaincodeStub_Expecter) GetDecorations() *MockChaincodeStub_GetDecorations_Call {
	return &MockChaincodeStub_GetDecorations_Call{Call: _e.mock.On("GetDecorations")}
}

func (_c *MockChaincodeStub_GetDecorations_Call) Run(run func()) *MockChaincodeStub_GetDecorations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChaincodeStub_GetDecorations_Call) Return(stringToBytes map[string][]byte) *MockChaincodeStub_GetDecorations_Call {
	_c.Call.Return(stringToBytes)
	return _c
}

func (_c *MockChaincodeStub_GetDecorations_Call) RunAndReturn(run func() map[string][]byte) *MockChaincodeStub_GetDecorations_Call {
	_c.Call.Return(run)
	return _c
}

// GetFunctionAndParameters provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetFunctionAndParameters() (string, []string) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFunctionAndParameters")
	}

	var r0 string
	var r1 []string
	if returnFunc, ok := ret.Get(0).(func() (string, []string)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() []string); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}
	return r0, r1
}

// MockChaincodeStub_GetFunctionAndParameters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFunctionAndParameters'
type MockChaincodeStub_GetFunctionAndParameters_Call struct {
	*mock.Call
}

// GetFunctionAndParameters is a helper method to define mock.On call
func (_e *MockChaincodeStub_Expecter) GetFunctionAndParameters() *MockChaincodeStub_GetFunctionAndParameters_Call {
	return &MockChaincodeStub_GetFunctionAndParameters_Call{Call: _e.mock.On("GetFunctionAndParameters")}
}

func (_c *MockChaincodeStub_GetFunctionAndParameters_Call) Run(run func()) *MockChaincodeStub_GetFunctionAndParameters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChaincodeStub_GetFunctionAndParameters_Call) Return(s string, strings []string) *MockChaincodeStub_GetFunctionAndParameters_Call {
	_c.Call.Return(s, strings)
	return _c
}

func (_c *MockChaincodeStub_GetFunctionAndParameters_Call) RunAndReturn(run func() (string, []string)) *MockChaincodeStub_GetFunctionAndParameters_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistoryForKey provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetHistoryForKey(key string) (shim.HistoryQueryIteratorInterface, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoryForKey")
	}

	var r0 shim.HistoryQueryIteratorInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (shim.HistoryQueryIteratorInterface, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) shim.HistoryQueryIteratorInterface); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shim.HistoryQueryIteratorInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetHistoryForKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistoryForKey'
type MockChaincodeStub_GetHistoryForKey_Call struct {
	*mock.Call
}

// GetHistoryForKey is a helper method to define mock.On call
//   - key
func (_e *MockChaincodeStub_Expecter) GetHistoryForKey(key interface{}) *MockChaincodeStub_GetHistoryForKey_Call {
	return &MockChaincodeStub_GetHistoryForKey_Call{Call: _e.mock.On("GetHistoryForKey", key)}
}

func (_c *MockChaincodeStub_GetHistoryForKey_Call) Run(run func(key string)) *MockChaincodeStub_GetHistoryForKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_GetHistoryForKey_Call) Return(historyQueryIteratorInterface shim.HistoryQueryIteratorInterface, err error) *MockChaincodeStub_GetHistoryForKey_Call {
	_c.Call.Return(historyQueryIteratorInterface, err)
	return _c
}

func (_c *MockChaincodeStub_GetHistoryForKey_Call) RunAndReturn(run func(key string) (shim.HistoryQueryIteratorInterface, error)) *MockChaincodeStub_GetHistoryForKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetMultiplePrivateData provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetMultiplePrivateData(collection string, keys ...string) ([][]byte, error) {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(collection, keys)
	} else {
		tmpRet = _mock.Called(collection)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetMultiplePrivateData")
	}

	var r0 [][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) ([][]byte, error)); ok {
		return returnFunc(collection, keys...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...string) [][]byte); ok {
		r0 = returnFunc(collection, keys...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...string) error); ok {
		r1 = returnFunc(collection, keys...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetMultiplePrivateData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMultiplePrivateData'
type MockChaincodeStub_GetMultiplePrivateData_Call struct {
	*mock.Call
}

// GetMultiplePrivateData is a helper method to define mock.On call
//   - collection
//   - keys
func (_e *MockChaincodeStub_Expecter) GetMultiplePrivateData(collection interface{}, keys ...interface{}) *MockChaincodeStub_GetMultiplePrivateData_Call {
	return &MockChaincodeStub_GetMultiplePrivateData_Call{Call: _e.mock.On("GetMultiplePrivateData",
		append([]interface{}{collection}, keys...)...)}
}

func (_c *MockChaincodeStub_GetMultiplePrivateData_Call) Run(run func(collection string, keys ...string)) *MockChaincodeStub_GetMultiplePrivateData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[1].([]string)
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockChaincodeStub_GetMultiplePrivateData_Call) Return(bytess [][]byte, err error) *MockChaincodeStub_GetMultiplePrivateData_Call {
	_c.Call.Return(bytess, err)
	return _c
}

func (_c *MockChaincodeStub_GetMultiplePrivateData_Call) RunAndReturn(run func(collection string, keys ...string) ([][]byte, error)) *MockChaincodeStub_GetMultiplePrivateData_Call {
	_c.Call.Return(run)
	return _c
}

// GetMultipleStates provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetMultipleStates(keys ...string) ([][]byte, error) {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(keys)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetMultipleStates")
	}

	var r0 [][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...string) ([][]byte, error)); ok {
		return returnFunc(keys...)
	}
	if returnFunc, ok := ret.Get(0).(func(...string) [][]byte); ok {
		r0 = returnFunc(keys...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...string) error); ok {
		r1 = returnFunc(keys...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetMultipleStates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMultipleStates'
type MockChaincodeStub_GetMultipleStates_Call struct {
	*mock.Call
}

// GetMultipleStates is a helper method to define mock.On call
//   - keys
func (_e *MockChaincodeStub_Expecter) GetMultipleStates(keys ...interface{}) *MockChaincodeStub_GetMultipleStates_Call {
	return &MockChaincodeStub_GetMultipleStates_Call{Call: _e.mock.On("GetMultipleStates",
		append([]interface{}{}, keys...)...)}
}

func (_c *MockChaincodeStub_GetMultipleStates_Call) Run(run func(keys ...string)) *MockChaincodeStub_GetMultipleStates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[0].([]string)
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockChaincodeStub_GetMultipleStates_Call) Return(bytess [][]byte, err error) *MockChaincodeStub_GetMultipleStates_Call {
	_c.Call.Return(bytess, err)
	return _c
}

func (_c *MockChaincodeStub_GetMultipleStates_Call) RunAndReturn(run func(keys ...string) ([][]byte, error)) *MockChaincodeStub_GetMultipleStates_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateData provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetPrivateData(collection string, key string) ([]byte, error) {
	ret := _mock.Called(collection, key)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateData")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]byte, error)); ok {
		return returnFunc(collection, key)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []byte); ok {
		r0 = returnFunc(collection, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(collection, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetPrivateData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateData'
type MockChaincodeStub_GetPrivateData_Call struct {
	*mock.Call
}

// GetPrivateData is a helper method to define mock.On call
//   - collection
//   - key
func (_e *MockChaincodeStub_Expecter) GetPrivateData(collection interface{}, key interface{}) *MockChaincodeStub_GetPrivateData_Call {
	return &MockChaincodeStub_GetPrivateData_Call{Call: _e.mock.On("GetPrivateData", collection, key)}
}

func (_c *MockChaincodeStub_GetPrivateData_Call) Run(run func(collection string, key string)) *MockChaincodeStub_GetPrivateData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_GetPrivateData_Call) Return(bytes []byte, err error) *MockChaincodeStub_GetPrivateData_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockChaincodeStub_GetPrivateData_Call) RunAndReturn(run func(collection string, key string) ([]byte, error)) *MockChaincodeStub_GetPrivateData_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateDataByPartialCompositeKey provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetPrivateDataByPartialCompositeKey(collection string, objectType string, keys []string) (shim.StateQueryIteratorInterface, error) {
	ret := _mock.Called(collection, objectType, keys)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateDataByPartialCompositeKey")
	}

	var r0 shim.StateQueryIteratorInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, []string) (shim.StateQueryIteratorInterface, error)); ok {
		return returnFunc(collection, objectType, keys)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, []string) shim.StateQueryIteratorInterface); ok {
		r0 = returnFunc(collection, objectType, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shim.StateQueryIteratorInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, []string) error); ok {
		r1 = returnFunc(collection, objectType, keys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetPrivateDataByPartialCompositeKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateDataByPartialCompositeKey'
type MockChaincodeStub_GetPrivateDataByPartialCompositeKey_Call struct {
	*mock.Call
}

// GetPrivateDataByPartialCompositeKey is a helper method to define mock.On call
//   - collection
//   - objectType
//   - keys
func (_e *MockChaincodeStub_Expecter) GetPrivateDataByPartialCompositeKey(collection interface{}, objectType interface{}, keys interface{}) *MockChaincodeStub_GetPrivateDataByPartialCompositeKey_Call {
	return &MockChaincodeStub_GetPrivateDataByPartialCompositeKey_Call{Call: _e.mock.On("GetPrivateDataByPartialCompositeKey", collection, objectType, keys)}
}

func (_c *MockChaincodeStub_GetPrivateDataByPartialCompositeKey_Call) Run(run func(collection string, objectType string, keys []string)) *MockChaincodeStub_GetPrivateDataByPartialCompositeKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockChaincodeStub_GetPrivateDataByPartialCompositeKey_Call) Return(stateQueryIteratorInterface shim.StateQueryIteratorInterface, err error) *MockChaincodeStub_GetPrivateDataByPartialCompositeKey_Call {
	_c.Call.Return(stateQueryIteratorInterface, err)
	return _c
}

func (_c *MockChaincodeStub_GetPrivateDataByPartialCompositeKey_Call) RunAndReturn(run func(collection string, objectType string, keys []string) (shim.StateQueryIteratorInterface, error)) *MockChaincodeStub_GetPrivateDataByPartialCompositeKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateDataByRange provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetPrivateDataByRange(collection string, startKey string, endKey string) (shim.StateQueryIteratorInterface, error) {
	ret := _mock.Called(collection, startKey, endKey)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateDataByRange")
	}

	var r0 shim.StateQueryIteratorInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (shim.StateQueryIteratorInterface, error)); ok {
		return returnFunc(collection, startKey, endKey)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) shim.StateQueryIteratorInterface); ok {
		r0 = returnFunc(collection, startKey, endKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shim.StateQueryIteratorInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(collection, startKey, endKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetPrivateDataByRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateDataByRange'
type MockChaincodeStub_GetPrivateDataByRange_Call struct {
	*mock.Call
}

// GetPrivateDataByRange is a helper method to define mock.On call
//   - collection
//   - startKey
//   - endKey
func (_e *MockChaincodeStub_Expecter) GetPrivateDataByRange(collection interface{}, startKey interface{}, endKey interface{}) *MockChaincodeStub_GetPrivateDataByRange_Call {
	return &MockChaincodeStub_GetPrivateDataByRange_Call{Call: _e.mock.On("GetPrivateDataByRange", collection, startKey, endKey)}
}

func (_c *MockChaincodeStub_GetPrivateDataByRange_Call) Run(run func(collection string, startKey string, endKey string)) *MockChaincodeStub_GetPrivateDataByRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_GetPrivateDataByRange_Call) Return(stateQueryIteratorInterface shim.StateQueryIteratorInterface, err error) *MockChaincodeStub_GetPrivateDataByRange_Call {
	_c.Call.Return(stateQueryIteratorInterface, err)
	return _c
}

func (_c *MockChaincodeStub_GetPrivateDataByRange_Call) RunAndReturn(run func(collection string, startKey string, endKey string) (shim.StateQueryIteratorInterface, error)) *MockChaincodeStub_GetPrivateDataByRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateDataHash provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetPrivateDataHash(collection string, key string) ([]byte, error) {
	ret := _mock.Called(collection, key)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateDataHash")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]byte, error)); ok {
		return returnFunc(collection, key)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []byte); ok {
		r0 = returnFunc(collection, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(collection, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetPrivateDataHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateDataHash'
type MockChaincodeStub_GetPrivateDataHash_Call struct {
	*mock.Call
}

// GetPrivateDataHash is a helper method to define mock.On call
//   - collection
//   - key
func (_e *MockChaincodeStub_Expecter) GetPrivateDataHash(collection interface{}, key interface{}) *MockChaincodeStub_GetPrivateDataHash_Call {
	return &MockChaincodeStub_GetPrivateDataHash_Call{Call: _e.mock.On("GetPrivateDataHash", collection, key)}
}

func (_c *MockChaincodeStub_GetPrivateDataHash_Call) Run(run func(collection string, key string)) *MockChaincodeStub_GetPrivateDataHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_GetPrivateDataHash_Call) Return(bytes []byte, err error) *MockChaincodeStub_GetPrivateDataHash_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockChaincodeStub_GetPrivateDataHash_Call) RunAndReturn(run func(collection string, key string) ([]byte, error)) *MockChaincodeStub_GetPrivateDataHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateDataQueryResult provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetPrivateDataQueryResult(collection string, query string) (shim.StateQueryIteratorInterface, error) {
	ret := _mock.Called(collection, query)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateDataQueryResult")
	}

	var r0 shim.StateQueryIteratorInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (shim.StateQueryIteratorInterface, error)); ok {
		return returnFunc(collection, query)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) shim.StateQueryIteratorInterface); ok {
		r0 = returnFunc(collection, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shim.StateQueryIteratorInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(collection, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetPrivateDataQueryResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateDataQueryResult'
type MockChaincodeStub_GetPrivateDataQueryResult_Call struct {
	*mock.Call
}

// GetPrivateDataQueryResult is a helper method to define mock.On call
//   - collection
//   - query
func (_e *MockChaincodeStub_Expecter) GetPrivateDataQueryResult(collection interface{}, query interface{}) *MockChaincodeStub_GetPrivateDataQueryResult_Call {
	return &MockChaincodeStub_GetPrivateDataQueryResult_Call{Call: _e.mock.On("GetPrivateDataQueryResult", collection, query)}
}

func (_c *MockChaincodeStub_GetPrivateDataQueryResult_Call) Run(run func(collection string, query string)) *MockChaincodeStub_GetPrivateDataQueryResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_GetPrivateDataQueryResult_Call) Return(stateQueryIteratorInterface shim.StateQueryIteratorInterface, err error) *MockChaincodeStub_GetPrivateDataQueryResult_Call {
	_c.Call.Return(stateQueryIteratorInterface, err)
	return _c
}

func (_c *MockChaincodeStub_GetPrivateDataQueryResult_Call) RunAndReturn(run func(collection string, query string) (shim.StateQueryIteratorInterface, error)) *MockChaincodeStub_GetPrivateDataQueryResult_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateDataValidationParameter provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetPrivateDataValidationParameter(collection string, key string) ([]byte, error) {
	ret := _mock.Called(collection, key)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateDataValidationParameter")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]byte, error)); ok {
		return returnFunc(collection, key)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []byte); ok {
		r0 = returnFunc(collection, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(collection, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetPrivateDataValidationParameter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateDataValidationParameter'
type MockChaincodeStub_GetPrivateDataValidationParameter_Call struct {
	*mock.Call
}

// GetPrivateDataValidationParameter is a helper method to define mock.On call
//   - collection
//   - key
func (_e *MockChaincodeStub_Expecter) GetPrivateDataValidationParameter(collection interface{}, key interface{}) *MockChaincodeStub_GetPrivateDataValidationParameter_Call {
	return &MockChaincodeStub_GetPrivateDataValidationParameter_Call{Call: _e.mock.On("GetPrivateDataValidationParameter", collection, key)}
}

func (_c *MockChaincodeStub_GetPrivateDataValidationParameter_Call) Run(run func(collection string, key string)) *MockChaincodeStub_GetPrivateDataValidationParameter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_GetPrivateDataValidationParameter_Call) Return(bytes []byte, err error) *MockChaincodeStub_GetPrivateDataValidationParameter_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockChaincodeStub_GetPrivateDataValidationParameter_Call) RunAndReturn(run func(collection string, key string) ([]byte, error)) *MockChaincodeStub_GetPrivateDataValidationParameter_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueryResult provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetQueryResult(query string) (shim.StateQueryIteratorInterface, error) {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for GetQueryResult")
	}

	var r0 shim.StateQueryIteratorInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (shim.StateQueryIteratorInterface, error)); ok {
		return returnFunc(query)
	}
	if returnFunc, ok := ret.Get(0).(func(string) shim.StateQueryIteratorInterface); ok {
		r0 = returnFunc(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shim.StateQueryIteratorInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetQueryResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueryResult'
type MockChaincodeStub_GetQueryResult_Call struct {
	*mock.Call
}

// GetQueryResult is a helper method to define mock.On call
//   - query
func (_e *MockChaincodeStub_Expecter) GetQueryResult(query interface{}) *MockChaincodeStub_GetQueryResult_Call {
	return &MockChaincodeStub_GetQueryResult_Call{Call: _e.mock.On("GetQueryResult", query)}
}

func (_c *MockChaincodeStub_GetQueryResult_Call) Run(run func(query string)) *MockChaincodeStub_GetQueryResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_GetQueryResult_Call) Return(stateQueryIteratorInterface shim.StateQueryIteratorInterface, err error) *MockChaincodeStub_GetQueryResult_Call {
	_c.Call.Return(stateQueryIteratorInterface, err)
	return _c
}

func (_c *MockChaincodeStub_GetQueryResult_Call) RunAndReturn(run func(query string) (shim.StateQueryIteratorInterface, error)) *MockChaincodeStub_GetQueryResult_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueryResultWithPagination provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetQueryResultWithPagination(query string, pageSize int32, bookmark string) (shim.StateQueryIteratorInterface, *peer.QueryResponseMetadata, error) {
	ret := _mock.Called(query, pageSize, bookmark)

	if len(ret) == 0 {
		panic("no return value specified for GetQueryResultWithPagination")
	}

	var r0 shim.StateQueryIteratorInterface
	var r1 *peer.QueryResponseMetadata
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, int32, string) (shim.StateQueryIteratorInterface, *peer.QueryResponseMetadata, error)); ok {
		return returnFunc(query, pageSize, bookmark)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int32, string) shim.StateQueryIteratorInterface); ok {
		r0 = returnFunc(query, pageSize, bookmark)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shim.StateQueryIteratorInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int32, string) *peer.QueryResponseMetadata); ok {
		r1 = returnFunc(query, pageSize, bookmark)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*peer.QueryResponseMetadata)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string, int32, string) error); ok {
		r2 = returnFunc(query, pageSize, bookmark)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockChaincodeStub_GetQueryResultWithPagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueryResultWithPagination'
type MockChaincodeStub_GetQueryResultWithPagination_Call struct {
	*mock.Call
}

// GetQueryResultWithPagination is a helper method to define mock.On call
//   - query
//   - pageSize
//   - bookmark
func (_e *MockChaincodeStub_Expecter) GetQueryResultWithPagination(query interface{}, pageSize interface{}, bookmark interface{}) *MockChaincodeStub_GetQueryResultWithPagination_Call {
	return &MockChaincodeStub_GetQueryResultWithPagination_Call{Call: _e.mock.On("GetQueryResultWithPagination", query, pageSize, bookmark)}
}

func (_c *MockChaincodeStub_GetQueryResultWithPagination_Call) Run(run func(query string, pageSize int32, bookmark string)) *MockChaincodeStub_GetQueryResultWithPagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int32), args[2].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_GetQueryResultWithPagination_Call) Return(stateQueryIteratorInterface shim.StateQueryIteratorInterface, queryResponseMetadata *peer.QueryResponseMetadata, err error) *MockChaincodeStub_GetQueryResultWithPagination_Call {
	_c.Call.Return(stateQueryIteratorInterface, queryResponseMetadata, err)
	return _c
}

func (_c *MockChaincodeStub_GetQueryResultWithPagination_Call) RunAndReturn(run func(query string, pageSize int32, bookmark string) (shim.StateQueryIteratorInterface, *peer.QueryResponseMetadata, error)) *MockChaincodeStub_GetQueryResultWithPagination_Call {
	_c.Call.Return(run)
	return _c
}

// GetSignedProposal provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetSignedProposal() (*peer.SignedProposal, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSignedProposal")
	}

	var r0 *peer.SignedProposal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*peer.SignedProposal, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *peer.SignedProposal); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*peer.SignedProposal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetSignedProposal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSignedProposal'
type MockChaincodeStub_GetSignedProposal_Call struct {
	*mock.Call
}

// GetSignedProposal is a helper method to define mock.On call
func (_e *MockChaincodeStub_Expecter) GetSignedProposal() *MockChaincodeStub_GetSignedProposal_Call {
	return &MockChaincodeStub_GetSignedProposal_Call{Call: _e.mock.On("GetSignedProposal")}
}

func (_c *MockChaincodeStub_GetSignedProposal_Call) Run(run func()) *MockChaincodeStub_GetSignedProposal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChaincodeStub_GetSignedProposal_Call) Return(signedProposal *peer.SignedProposal, err error) *MockChaincodeStub_GetSignedProposal_Call {
	_c.Call.Return(signedProposal, err)
	return _c
}

func (_c *MockChaincodeStub_GetSignedProposal_Call) RunAndReturn(run func() (*peer.SignedProposal, error)) *MockChaincodeStub_GetSignedProposal_Call {
	_c.Call.Return(run)
	return _c
}

// GetState provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetState(key string) ([]byte, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type MockChaincodeStub_GetState_Call struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
//   - key
func (_e *MockChaincodeStub_Expecter) GetState(key interface{}) *MockChaincodeStub_GetState_Call {
	return &MockChaincodeStub_GetState_Call{Call: _e.mock.On("GetState", key)}
}

func (_c *MockChaincodeStub_GetState_Call) Run(run func(key string)) *MockChaincodeStub_GetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_GetState_Call) Return(bytes []byte, err error) *MockChaincodeStub_GetState_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockChaincodeStub_GetState_Call) RunAndReturn(run func(key string) ([]byte, error)) *MockChaincodeStub_GetState_Call {
	_c.Call.Return(run)
	return _c
}

// GetStateByPartialCompositeKey provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetStateByPartialCompositeKey(objectType string, keys []string) (shim.StateQueryIteratorInterface, error) {
	ret := _mock.Called(objectType, keys)

	if len(ret) == 0 {
		panic("no return value specified for GetStateByPartialCompositeKey")
	}

	var r0 shim.StateQueryIteratorInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []string) (shim.StateQueryIteratorInterface, error)); ok {
		return returnFunc(objectType, keys)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []string) shim.StateQueryIteratorInterface); ok {
		r0 = returnFunc(objectType, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shim.StateQueryIteratorInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []string) error); ok {
		r1 = returnFunc(objectType, keys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetStateByPartialCompositeKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStateByPartialCompositeKey'
type MockChaincodeStub_GetStateByPartialCompositeKey_Call struct {
	*mock.Call
}

// GetStateByPartialCompositeKey is a helper method to define mock.On call
//   - objectType
//   - keys
func (_e *MockChaincodeStub_Expecter) GetStateByPartialCompositeKey(objectType interface{}, keys interface{}) *MockChaincodeStub_GetStateByPartialCompositeKey_Call {
	return &MockChaincodeStub_GetStateByPartialCompositeKey_Call{Call: _e.mock.On("GetStateByPartialCompositeKey", objectType, keys)}
}

func (_c *MockChaincodeStub_GetStateByPartialCompositeKey_Call) Run(run func(objectType string, keys []string)) *MockChaincodeStub_GetStateByPartialCompositeKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string))
	})
	return _c
}

func (_c *MockChaincodeStub_GetStateByPartialCompositeKey_Call) Return(stateQueryIteratorInterface shim.StateQueryIteratorInterface, err error) *MockChaincodeStub_GetStateByPartialCompositeKey_Call {
	_c.Call.Return(stateQueryIteratorInterface, err)
	return _c
}

func (_c *MockChaincodeStub_GetStateByPartialCompositeKey_Call) RunAndReturn(run func(objectType string, keys []string) (shim.StateQueryIteratorInterface, error)) *MockChaincodeStub_GetStateByPartialCompositeKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetStateByPartialCompositeKeyWithPagination provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetStateByPartialCompositeKeyWithPagination(objectType string, keys []string, pageSize int32, bookmark string) (shim.StateQueryIteratorInterface, *peer.QueryResponseMetadata, error) {
	ret := _mock.Called(objectType, keys, pageSize, bookmark)

	if len(ret) == 0 {
		panic("no return value specified for GetStateByPartialCompositeKeyWithPagination")
	}

	var r0 shim.StateQueryIteratorInterface
	var r1 *peer.QueryResponseMetadata
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, []string, int32, string) (shim.StateQueryIteratorInterface, *peer.QueryResponseMetadata, error)); ok {
		return returnFunc(objectType, keys, pageSize, bookmark)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []string, int32, string) shim.StateQueryIteratorInterface); ok {
		r0 = returnFunc(objectType, keys, pageSize, bookmark)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shim.StateQueryIteratorInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []string, int32, string) *peer.QueryResponseMetadata); ok {
		r1 = returnFunc(objectType, keys, pageSize, bookmark)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*peer.QueryResponseMetadata)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string, []string, int32, string) error); ok {
		r2 = returnFunc(objectType, keys, pageSize, bookmark)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockChaincodeStub_GetStateByPartialCompositeKeyWithPagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStateByPartialCompositeKeyWithPagination'
type MockChaincodeStub_GetStateByPartialCompositeKeyWithPagination_Call struct {
	*mock.Call
}

// GetStateByPartialCompositeKeyWithPagination is a helper method to define mock.On call
//   - objectType
//   - keys
//   - pageSize
//   - bookmark
func (_e *MockChaincodeStub_Expecter) GetStateByPartialCompositeKeyWithPagination(objectType interface{}, keys interface{}, pageSize interface{}, bookmark interface{}) *MockChaincodeStub_GetStateByPartialCompositeKeyWithPagination_Call {
	return &MockChaincodeStub_GetStateByPartialCompositeKeyWithPagination_Call{Call: _e.mock.On("GetStateByPartialCompositeKeyWithPagination", objectType, keys, pageSize, bookmark)}
}

func (_c *MockChaincodeStub_GetStateByPartialCompositeKeyWithPagination_Call) Run(run func(objectType string, keys []string, pageSize int32, bookmark string)) *MockChaincodeStub_GetStateByPartialCompositeKeyWithPagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]string), args[2].(int32), args[3].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_GetStateByPartialCompositeKeyWithPagination_Call) Return(stateQueryIteratorInterface shim.StateQueryIteratorInterface, queryResponseMetadata *peer.QueryResponseMetadata, err error) *MockChaincodeStub_GetStateByPartialCompositeKeyWithPagination_Call {
	_c.Call.Return(stateQueryIteratorInterface, queryResponseMetadata, err)
	return _c
}

func (_c *MockChaincodeStub_GetStateByPartialCompositeKeyWithPagination_Call) RunAndReturn(run func(objectType string, keys []string, pageSize int32, bookmark string) (shim.StateQueryIteratorInterface, *peer.QueryResponseMetadata, error)) *MockChaincodeStub_GetStateByPartialCompositeKeyWithPagination_Call {
	_c.Call.Return(run)
	return _c
}

// GetStateByRange provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetStateByRange(startKey string, endKey string) (shim.StateQueryIteratorInterface, error) {
	ret := _mock.Called(startKey, endKey)

	if len(ret) == 0 {
		panic("no return value specified for GetStateByRange")
	}

	var r0 shim.StateQueryIteratorInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (shim.StateQueryIteratorInterface, error)); ok {
		return returnFunc(startKey, endKey)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) shim.StateQueryIteratorInterface); ok {
		r0 = returnFunc(startKey, endKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shim.StateQueryIteratorInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(startKey, endKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetStateByRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStateByRange'
type MockChaincodeStub_GetStateByRange_Call struct {
	*mock.Call
}

// GetStateByRange is a helper method to define mock.On call
//   - startKey
//   - endKey
func (_e *MockChaincodeStub_Expecter) GetStateByRange(startKey interface{}, endKey interface{}) *MockChaincodeStub_GetStateByRange_Call {
	return &MockChaincodeStub_GetStateByRange_Call{Call: _e.mock.On("GetStateByRange", startKey, endKey)}
}

func (_c *MockChaincodeStub_GetStateByRange_Call) Run(run func(startKey string, endKey string)) *MockChaincodeStub_GetStateByRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_GetStateByRange_Call) Return(stateQueryIteratorInterface shim.StateQueryIteratorInterface, err error) *MockChaincodeStub_GetStateByRange_Call {
	_c.Call.Return(stateQueryIteratorInterface, err)
	return _c
}

func (_c *MockChaincodeStub_GetStateByRange_Call) RunAndReturn(run func(startKey string, endKey string) (shim.StateQueryIteratorInterface, error)) *MockChaincodeStub_GetStateByRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetStateByRangeWithPagination provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetStateByRangeWithPagination(startKey string, endKey string, pageSize int32, bookmark string) (shim.StateQueryIteratorInterface, *peer.QueryResponseMetadata, error) {
	ret := _mock.Called(startKey, endKey, pageSize, bookmark)

	if len(ret) == 0 {
		panic("no return value specified for GetStateByRangeWithPagination")
	}

	var r0 shim.StateQueryIteratorInterface
	var r1 *peer.QueryResponseMetadata
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string, int32, string) (shim.StateQueryIteratorInterface, *peer.QueryResponseMetadata, error)); ok {
		return returnFunc(startKey, endKey, pageSize, bookmark)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, int32, string) shim.StateQueryIteratorInterface); ok {
		r0 = returnFunc(startKey, endKey, pageSize, bookmark)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shim.StateQueryIteratorInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, int32, string) *peer.QueryResponseMetadata); ok {
		r1 = returnFunc(startKey, endKey, pageSize, bookmark)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*peer.QueryResponseMetadata)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string, string, int32, string) error); ok {
		r2 = returnFunc(startKey, endKey, pageSize, bookmark)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockChaincodeStub_GetStateByRangeWithPagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStateByRangeWithPagination'
type MockChaincodeStub_GetStateByRangeWithPagination_Call struct {
	*mock.Call
}

// GetStateByRangeWithPagination is a helper method to define mock.On call
//   - startKey
//   - endKey
//   - pageSize
//   - bookmark
func (_e *MockChaincodeStub_Expecter) GetStateByRangeWithPagination(startKey interface{}, endKey interface{}, pageSize interface{}, bookmark interface{}) *MockChaincodeStub_GetStateByRangeWithPagination_Call {
	return &MockChaincodeStub_GetStateByRangeWithPagination_Call{Call: _e.mock.On("GetStateByRangeWithPagination", startKey, endKey, pageSize, bookmark)}
}

func (_c *MockChaincodeStub_GetStateByRangeWithPagination_Call) Run(run func(startKey string, endKey string, pageSize int32, bookmark string)) *MockChaincodeStub_GetStateByRangeWithPagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(int32), args[3].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_GetStateByRangeWithPagination_Call) Return(stateQueryIteratorInterface shim.StateQueryIteratorInterface, queryResponseMetadata *peer.QueryResponseMetadata, err error) *MockChaincodeStub_GetStateByRangeWithPagination_Call {
	_c.Call.Return(stateQueryIteratorInterface, queryResponseMetadata, err)
	return _c
}

func (_c *MockChaincodeStub_GetStateByRangeWithPagination_Call) RunAndReturn(run func(startKey string, endKey string, pageSize int32, bookmark string) (shim.StateQueryIteratorInterface, *peer.QueryResponseMetadata, error)) *MockChaincodeStub_GetStateByRangeWithPagination_Call {
	_c.Call.Return(run)
	return _c
}

// GetStateValidationParameter provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetStateValidationParameter(key string) ([]byte, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetStateValidationParameter")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetStateValidationParameter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStateValidationParameter'
type MockChaincodeStub_GetStateValidationParameter_Call struct {
	*mock.Call
}

// GetStateValidationParameter is a helper method to define mock.On call
//   - key
func (_e *MockChaincodeStub_Expecter) GetStateValidationParameter(key interface{}) *MockChaincodeStub_GetStateValidationParameter_Call {
	return &MockChaincodeStub_GetStateValidationParameter_Call{Call: _e.mock.On("GetStateValidationParameter", key)}
}

func (_c *MockChaincodeStub_GetStateValidationParameter_Call) Run(run func(key string)) *MockChaincodeStub_GetStateValidationParameter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_GetStateValidationParameter_Call) Return(bytes []byte, err error) *MockChaincodeStub_GetStateValidationParameter_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockChaincodeStub_GetStateValidationParameter_Call) RunAndReturn(run func(key string) ([]byte, error)) *MockChaincodeStub_GetStateValidationParameter_Call {
	_c.Call.Return(run)
	return _c
}

// GetStringArgs provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetStringArgs() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStringArgs")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockChaincodeStub_GetStringArgs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStringArgs'
type MockChaincodeStub_GetStringArgs_Call struct {
	*mock.Call
}

// GetStringArgs is a helper method to define mock.On call
func (_e *MockChaincodeStub_Expecter) GetStringArgs() *MockChaincodeStub_GetStringArgs_Call {
	return &MockChaincodeStub_GetStringArgs_Call{Call: _e.mock.On("GetStringArgs")}
}

func (_c *MockChaincodeStub_GetStringArgs_Call) Run(run func()) *MockChaincodeStub_GetStringArgs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChaincodeStub_GetStringArgs_Call) Return(strings []string) *MockChaincodeStub_GetStringArgs_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockChaincodeStub_GetStringArgs_Call) RunAndReturn(run func() []string) *MockChaincodeStub_GetStringArgs_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransient provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetTransient() (map[string][]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTransient")
	}

	var r0 map[string][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (map[string][]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[string][]byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetTransient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransient'
type MockChaincodeStub_GetTransient_Call struct {
	*mock.Call
}

// GetTransient is a helper method to define mock.On call
func (_e *MockChaincodeStub_Expecter) GetTransient() *MockChaincodeStub_GetTransient_Call {
	return &MockChaincodeStub_GetTransient_Call{Call: _e.mock.On("GetTransient")}
}

func (_c *MockChaincodeStub_GetTransient_Call) Run(run func()) *MockChaincodeStub_GetTransient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChaincodeStub_GetTransient_Call) Return(stringToBytes map[string][]byte, err error) *MockChaincodeStub_GetTransient_Call {
	_c.Call.Return(stringToBytes, err)
	return _c
}

func (_c *MockChaincodeStub_GetTransient_Call) RunAndReturn(run func() (map[string][]byte, error)) *MockChaincodeStub_GetTransient_Call {
	_c.Call.Return(run)
	return _c
}

// GetTxID provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetTxID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTxID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockChaincodeStub_GetTxID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTxID'
type MockChaincodeStub_GetTxID_Call struct {
	*mock.Call
}

// GetTxID is a helper method to define mock.On call
func (_e *MockChaincodeStub_Expecter) GetTxID() *MockChaincodeStub_GetTxID_Call {
	return &MockChaincodeStub_GetTxID_Call{Call: _e.mock.On("GetTxID")}
}

func (_c *MockChaincodeStub_GetTxID_Call) Run(run func()) *MockChaincodeStub_GetTxID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChaincodeStub_GetTxID_Call) Return(s string) *MockChaincodeStub_GetTxID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockChaincodeStub_GetTxID_Call) RunAndReturn(run func() string) *MockChaincodeStub_GetTxID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTxTimestamp provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) GetTxTimestamp() (*timestamppb.Timestamp, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTxTimestamp")
	}

	var r0 *timestamppb.Timestamp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*timestamppb.Timestamp, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *timestamppb.Timestamp); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*timestamppb.Timestamp)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChaincodeStub_GetTxTimestamp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTxTimestamp'
type MockChaincodeStub_GetTxTimestamp_Call struct {
	*mock.Call
}

// GetTxTimestamp is a helper method to define mock.On call
func (_e *MockChaincodeStub_Expecter) GetTxTimestamp() *MockChaincodeStub_GetTxTimestamp_Call {
	return &MockChaincodeStub_GetTxTimestamp_Call{Call: _e.mock.On("GetTxTimestamp")}
}

func (_c *MockChaincodeStub_GetTxTimestamp_Call) Run(run func()) *MockChaincodeStub_GetTxTimestamp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChaincodeStub_GetTxTimestamp_Call) Return(timestamp *timestamppb.Timestamp, err error) *MockChaincodeStub_GetTxTimestamp_Call {
	_c.Call.Return(timestamp, err)
	return _c
}

func (_c *MockChaincodeStub_GetTxTimestamp_Call) RunAndReturn(run func() (*timestamppb.Timestamp, error)) *MockChaincodeStub_GetTxTimestamp_Call {
	_c.Call.Return(run)
	return _c
}

// InvokeChaincode provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) InvokeChaincode(chaincodeName string, args [][]byte, channel string) *peer.Response {
	ret := _mock.Called(chaincodeName, args, channel)

	if len(ret) == 0 {
		panic("no return value specified for InvokeChaincode")
	}

	var r0 *peer.Response
	if returnFunc, ok := ret.Get(0).(func(string, [][]byte, string) *peer.Response); ok {
		r0 = returnFunc(chaincodeName, args, channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*peer.Response)
		}
	}
	return r0
}

// MockChaincodeStub_InvokeChaincode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvokeChaincode'
type MockChaincodeStub_InvokeChaincode_Call struct {
	*mock.Call
}

// InvokeChaincode is a helper method to define mock.On call
//   - chaincodeName
//   - args
//   - channel
func (_e *MockChaincodeStub_Expecter) InvokeChaincode(chaincodeName interface{}, args interface{}, channel interface{}) *MockChaincodeStub_InvokeChaincode_Call {
	return &MockChaincodeStub_InvokeChaincode_Call{Call: _e.mock.On("InvokeChaincode", chaincodeName, args, channel)}
}

func (_c *MockChaincodeStub_InvokeChaincode_Call) Run(run func(chaincodeName string, args [][]byte, channel string)) *MockChaincodeStub_InvokeChaincode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([][]byte), args[2].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_InvokeChaincode_Call) Return(response *peer.Response) *MockChaincodeStub_InvokeChaincode_Call {
	_c.Call.Return(response)
	return _c
}

func (_c *MockChaincodeStub_InvokeChaincode_Call) RunAndReturn(run func(chaincodeName string, args [][]byte, channel string) *peer.Response) *MockChaincodeStub_InvokeChaincode_Call {
	_c.Call.Return(run)
	return _c
}

// PurgePrivateData provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) PurgePrivateData(collection string, key string) error {
	ret := _mock.Called(collection, key)

	if len(ret) == 0 {
		panic("no return value specified for PurgePrivateData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(collection, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChaincodeStub_PurgePrivateData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgePrivateData'
type MockChaincodeStub_PurgePrivateData_Call struct {
	*mock.Call
}

// PurgePrivateData is a helper method to define mock.On call
//   - collection
//   - key
func (_e *MockChaincodeStub_Expecter) PurgePrivateData(collection interface{}, key interface{}) *MockChaincodeStub_PurgePrivateData_Call {
	return &MockChaincodeStub_PurgePrivateData_Call{Call: _e.mock.On("PurgePrivateData", collection, key)}
}

func (_c *MockChaincodeStub_PurgePrivateData_Call) Run(run func(collection string, key string)) *MockChaincodeStub_PurgePrivateData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_PurgePrivateData_Call) Return(err error) *MockChaincodeStub_PurgePrivateData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChaincodeStub_PurgePrivateData_Call) RunAndReturn(run func(collection string, key string) error) *MockChaincodeStub_PurgePrivateData_Call {
	_c.Call.Return(run)
	return _c
}

// PutPrivateData provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) PutPrivateData(collection string, key string, value []byte) error {
	ret := _mock.Called(collection, key, value)

	if len(ret) == 0 {
		panic("no return value specified for PutPrivateData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, []byte) error); ok {
		r0 = returnFunc(collection, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChaincodeStub_PutPrivateData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutPrivateData'
type MockChaincodeStub_PutPrivateData_Call struct {
	*mock.Call
}

// PutPrivateData is a helper method to define mock.On call
//   - collection
//   - key
//   - value
func (_e *MockChaincodeStub_Expecter) PutPrivateData(collection interface{}, key interface{}, value interface{}) *MockChaincodeStub_PutPrivateData_Call {
	return &MockChaincodeStub_PutPrivateData_Call{Call: _e.mock.On("PutPrivateData", collection, key, value)}
}

func (_c *MockChaincodeStub_PutPrivateData_Call) Run(run func(collection string, key string, value []byte)) *MockChaincodeStub_PutPrivateData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockChaincodeStub_PutPrivateData_Call) Return(err error) *MockChaincodeStub_PutPrivateData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChaincodeStub_PutPrivateData_Call) RunAndReturn(run func(collection string, key string, value []byte) error) *MockChaincodeStub_PutPrivateData_Call {
	_c.Call.Return(run)
	return _c
}

// PutState provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) PutState(key string, value []byte) error {
	ret := _mock.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for PutState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChaincodeStub_PutState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutState'
type MockChaincodeStub_PutState_Call struct {
	*mock.Call
}

// PutState is a helper method to define mock.On call
//   - key
//   - value
func (_e *MockChaincodeStub_Expecter) PutState(key interface{}, value interface{}) *MockChaincodeStub_PutState_Call {
	return &MockChaincodeStub_PutState_Call{Call: _e.mock.On("PutState", key, value)}
}

func (_c *MockChaincodeStub_PutState_Call) Run(run func(key string, value []byte)) *MockChaincodeStub_PutState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte))
	})
	return _c
}

func (_c *MockChaincodeStub_PutState_Call) Return(err error) *MockChaincodeStub_PutState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChaincodeStub_PutState_Call) RunAndReturn(run func(key string, value []byte) error) *MockChaincodeStub_PutState_Call {
	_c.Call.Return(run)
	return _c
}

// SetEvent provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) SetEvent(name string, payload []byte) error {
	ret := _mock.Called(name, payload)

	if len(ret) == 0 {
		panic("no return value specified for SetEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(name, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChaincodeStub_SetEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetEvent'
type MockChaincodeStub_SetEvent_Call struct {
	*mock.Call
}

// SetEvent is a helper method to define mock.On call
//   - name
//   - payload
func (_e *MockChaincodeStub_Expecter) SetEvent(name interface{}, payload interface{}) *MockChaincodeStub_SetEvent_Call {
	return &MockChaincodeStub_SetEvent_Call{Call: _e.mock.On("SetEvent", name, payload)}
}

func (_c *MockChaincodeStub_SetEvent_Call) Run(run func(name string, payload []byte)) *MockChaincodeStub_SetEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte))
	})
	return _c
}

func (_c *MockChaincodeStub_SetEvent_Call) Return(err error) *MockChaincodeStub_SetEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChaincodeStub_SetEvent_Call) RunAndReturn(run func(name string, payload []byte) error) *MockChaincodeStub_SetEvent_Call {
	_c.Call.Return(run)
	return _c
}

// SetPrivateDataValidationParameter provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) SetPrivateDataValidationParameter(collection string, key string, ep []byte) error {
	ret := _mock.Called(collection, key, ep)

	if len(ret) == 0 {
		panic("no return value specified for SetPrivateDataValidationParameter")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, []byte) error); ok {
		r0 = returnFunc(collection, key, ep)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChaincodeStub_SetPrivateDataValidationParameter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPrivateDataValidationParameter'
type MockChaincodeStub_SetPrivateDataValidationParameter_Call struct {
	*mock.Call
}

// SetPrivateDataValidationParameter is a helper method to define mock.On call
//   - collection
//   - key
//   - ep
func (_e *MockChaincodeStub_Expecter) SetPrivateDataValidationParameter(collection interface{}, key interface{}, ep interface{}) *MockChaincodeStub_SetPrivateDataValidationParameter_Call {
	return &MockChaincodeStub_SetPrivateDataValidationParameter_Call{Call: _e.mock.On("SetPrivateDataValidationParameter", collection, key, ep)}
}

func (_c *MockChaincodeStub_SetPrivateDataValidationParameter_Call) Run(run func(collection string, key string, ep []byte)) *MockChaincodeStub_SetPrivateDataValidationParameter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockChaincodeStub_SetPrivateDataValidationParameter_Call) Return(err error) *MockChaincodeStub_SetPrivateDataValidationParameter_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChaincodeStub_SetPrivateDataValidationParameter_Call) RunAndReturn(run func(collection string, key string, ep []byte) error) *MockChaincodeStub_SetPrivateDataValidationParameter_Call {
	_c.Call.Return(run)
	return _c
}

// SetStateValidationParameter provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) SetStateValidationParameter(key string, ep []byte) error {
	ret := _mock.Called(key, ep)

	if len(ret) == 0 {
		panic("no return value specified for SetStateValidationParameter")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = returnFunc(key, ep)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChaincodeStub_SetStateValidationParameter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStateValidationParameter'
type MockChaincodeStub_SetStateValidationParameter_Call struct {
	*mock.Call
}

// SetStateValidationParameter is a helper method to define mock.On call
//   - key
//   - ep
func (_e *MockChaincodeStub_Expecter) SetStateValidationParameter(key interface{}, ep interface{}) *MockChaincodeStub_SetStateValidationParameter_Call {
	return &MockChaincodeStub_SetStateValidationParameter_Call{Call: _e.mock.On("SetStateValidationParameter", key, ep)}
}

func (_c *MockChaincodeStub_SetStateValidationParameter_Call) Run(run func(key string, ep []byte)) *MockChaincodeStub_SetStateValidationParameter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte))
	})
	return _c
}

func (_c *MockChaincodeStub_SetStateValidationParameter_Call) Return(err error) *MockChaincodeStub_SetStateValidationParameter_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChaincodeStub_SetStateValidationParameter_Call) RunAndReturn(run func(key string, ep []byte) error) *MockChaincodeStub_SetStateValidationParameter_Call {
	_c.Call.Return(run)
	return _c
}

// SplitCompositeKey provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) SplitCompositeKey(compositeKey string) (string, []string, error) {
	ret := _mock.Called(compositeKey)

	if len(ret) == 0 {
		panic("no return value specified for SplitCompositeKey")
	}

	var r0 string
	var r1 []string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, []string, error)); ok {
		return returnFunc(compositeKey)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(compositeKey)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) []string); ok {
		r1 = returnFunc(compositeKey)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(compositeKey)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockChaincodeStub_SplitCompositeKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SplitCompositeKey'
type MockChaincodeStub_SplitCompositeKey_Call struct {
	*mock.Call
}

// SplitCompositeKey is a helper method to define mock.On call
//   - compositeKey
func (_e *MockChaincodeStub_Expecter) SplitCompositeKey(compositeKey interface{}) *MockChaincodeStub_SplitCompositeKey_Call {
	return &MockChaincodeStub_SplitCompositeKey_Call{Call: _e.mock.On("SplitCompositeKey", compositeKey)}
}

func (_c *MockChaincodeStub_SplitCompositeKey_Call) Run(run func(compositeKey string)) *MockChaincodeStub_SplitCompositeKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockChaincodeStub_SplitCompositeKey_Call) Return(s string, strings []string, err error) *MockChaincodeStub_SplitCompositeKey_Call {
	_c.Call.Return(s, strings, err)
	return _c
}

func (_c *MockChaincodeStub_SplitCompositeKey_Call) RunAndReturn(run func(compositeKey string) (string, []string, error)) *MockChaincodeStub_SplitCompositeKey_Call {
	_c.Call.Return(run)
	return _c
}

// StartWriteBatch provides a mock function for the type MockChaincodeStub
func (_mock *MockChaincodeStub) StartWriteBatch() {
	_mock.Called()
	return
}

// MockChaincodeStub_StartWriteBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartWriteBatch'
type MockChaincodeStub_StartWriteBatch_Call struct {
	*mock.Call
}

// StartWriteBatch is a helper method to define mock.On call
func (_e *MockChaincodeStub_Expecter) StartWriteBatch() *MockChaincodeStub_StartWriteBatch_Call {
	return &MockChaincodeStub_StartWriteBatch_Call{Call: _e.mock.On("StartWriteBatch")}
}

func (_c *MockChaincodeStub_StartWriteBatch_Call) Run(run func()) *MockChaincodeStub_StartWriteBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChaincodeStub_StartWriteBatch_Call) Return() *MockChaincodeStub_StartWriteBatch_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockChaincodeStub_StartWriteBatch_Call) RunAndReturn(run func()) *MockChaincodeStub_StartWriteBatch_Call {
	_c.Run(run)
	return _c
}
