# Copyright the Hyperledger Fabric contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
  batch: false
  branches:
    include:
      - master

variables:
  branch: $[ coalesce(variables['system.PullRequest.TargetBranch'], variables['build.SourceBranchName']) ]

pool:
  vmImage: ubuntu-16.04
container:
  image: awjh/fabric-contract-api-go-env:0.0.1

steps:
  - checkout: self
    clean: true
    fetchDepth: 1

  - script: .azure-pipelines/scripts/lint.sh
    displayName: Vet and lint

  - script: license-check-and-add check -f license-config.json
    displayName: Check licenses

  - script: go test -race ./... -v
    displayName: Run tests

  - script: go get -u github.com/DATA-DOG/godog/cmd/godog
    displayName: Install Godog

  - script: cd internal/functionaltests && godog
    displayName: Run Functional Tests

  - script: .azure-pipelines/scripts/release-checks.sh $(Build.SourceBranchName)
    displayName: Release checklist
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags'))

