# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

steps:
    - task: NodeTool@0 
      inputs:
        versionSpec: 12.x
      displayName: Install Node
    - script: |
        npm install -g license-check-and-add@3.0.3
        npm install -g fabric-chaincode-integration@0.5.0-2020921131117
      displayName: Install NPM Globals
    - task: GoTool@0
      inputs:
        version: $(GOVER)
        goPath: $(GOPATH)
        goBin: $(GOBIN)
      displayName: Install GoLang
    - script: |
        GO111MODULE=on go get github.com/cucumber/godog/cmd/godog@v0.8.0
        go get -u golang.org/x/lint/golint
        go get -u golang.org/x/tools/cmd/goimports
      displayName: Install GoLang tools
    - script: |
        docker pull gomods/athens:v0.7.2
